### ISSUE TITLE
NewAddressFromPK 生成的地址不对

### ISSUE THREAD

**Issue by wehnhew** [chuwt/chia-address-generator#1]
```
NewAddressFromPKHex(
   "90d7f1d21eb3f4111dea5bb1ab20294dcb992ab53bf492d1682850e1ec944ca82efdfa920aa68483ec3e5e1d74df577c",
   "xch",
)
```

上面生成的结果为：xch1y2xhqxus3dql5h5e4a609t4rxrmxmegs7wah400uprawextr0qaqsatr6
而用奇亚生成的结果为：xch1qr5krpjkvmcy5tn7s76ldqq39n32xa9jkajz8ednjgnu4gmjaqzs7pew7s

**Comment by chuwt** [comment]
Oh, 多谢，看样子我的测试还不严谨哈哈哈。后面修复哈。同时欢迎PR！

**Comment by chuwt** [comment]
@wehnhew Hi friend. Fixed now.

**Comment by wehnhew** [comment]
> @wehnhew Hi friend. Fixed now.
good job，thanks!
